export default function TermsOfUse() {
  return (
    <main className="min-h-screen bg-[#0a0f1e] text-slate-300 px-4 md:px-8 py-16 max-w-4xl mx-auto">
      <h1 className="text-3xl font-bold text-white mb-2">Terms of Use</h1>
      <p className="text-slate-500 text-sm mb-10">Effective Date: [Insert Date] &nbsp;|&nbsp; Website: https://www.jobslostlive.com</p>
      <section className="space-y-10 text-sm leading-relaxed">
        <div><h2 className="text-lg font-semibold text-white mb-2">1. Acceptance of Terms</h2><p>By accessing or using JobsLostLive, you agree to be bound by these Terms of Use (&quot;Terms&quot;). If you do not agree to these Terms, do not use this website.</p></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">2. Description of Service</h2><p>JobsLostLive is an informational dashboard that aggregates publicly available data on layoffs and AI-related workforce displacement from government, academic, and industry sources.</p><p className="mt-3">JobsLostLive is provided for informational and educational purposes only. We do not provide legal, financial, employment, or career advice.</p></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">3. User-Submitted Content</h2><h3 className="font-semibold text-slate-200 mt-4 mb-1">3.1 User Content</h3><p>You may submit personal stories, experiences, and comments related to layoffs and AI displacement. You are solely responsible for any User Content you submit.</p><h3 className="font-semibold text-slate-200 mt-4 mb-1">3.2 Content Standards</h3><p>You agree that your User Content will not:</p><ul className="list-disc list-inside mt-2 space-y-1 text-slate-400"><li>Contain false, defamatory, libelous, or misleading statements.</li><li>Include personal information of others without their consent.</li><li>Violate any person&apos;s privacy, publicity rights, or intellectual property rights.</li><li>Contain discriminatory, harassing, threatening, hateful, or unlawful material.</li><li>Impersonate any person or entity.</li><li>Contain spam, malware, or unsolicited commercial messages.</li></ul><h3 className="font-semibold text-slate-200 mt-4 mb-1">3.3 License to JobsLostLive</h3><p>By submitting User Content, you grant JobsLostLive a worldwide, non-exclusive, royalty-free, perpetual, irrevocable license to use, reproduce, modify, publish, and distribute such content. You retain ownership.</p><h3 className="font-semibold text-slate-200 mt-4 mb-1">3.4 No Expectation of Confidentiality</h3><p>User Content is not confidential. Do not submit proprietary or sensitive information.</p><h3 className="font-semibold text-slate-200 mt-4 mb-1">3.5 Moderation and Removal</h3><p>We reserve the right to review, edit, or remove any User Content at any time without prior notice.</p></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">4. Data Sources, Accuracy, and Limitations</h2><p>Data is sourced from publicly available reports including:</p><ul className="list-disc list-inside mt-2 space-y-1 text-slate-400"><li>U.S. Bureau of Labor Statistics (BLS)</li><li>Challenger, Gray &amp; Christmas</li><li>Federal Reserve Economic Data (FRED)</li><li>Layoffs.fyi and similar layoff trackers</li><li>McKinsey Global Institute</li><li>Oxford University and other research institutions</li><li>Public news and media reports</li></ul><p className="mt-3">The animated counter is a mathematical extrapolation based on known annual run rates and is not a real-time measurement. All data is provided for informational purposes only.</p></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">5. No Professional Advice</h2><p>Nothing on JobsLostLive constitutes legal, financial, tax, investment, or career advice. Your use of this site is at your own risk.</p></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">6. User Conduct</h2><ul className="list-disc list-inside mt-2 space-y-1 text-slate-400"><li>Do not interfere with or disrupt the operation of the website.</li><li>Do not attempt unauthorized access to any part of the website.</li><li>Do not use automated tools or scrapers without prior written permission.</li><li>Do not circumvent any security or access control measures.</li></ul></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">7. Intellectual Property</h2><p>All content on JobsLostLive is owned by JobsLostLive or its licensors and protected by copyright law. You may use the website for personal, non-commercial purposes only.</p></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">8. Third-Party Links</h2><p>We do not control, endorse, or assume responsibility for any third-party websites or content.</p></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">9. Disclaimer of Warranties</h2><p>JobsLostLive is provided on an &quot;as is&quot; and &quot;as available&quot; basis. We disclaim all warranties, express or implied.</p></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">10. Limitation of Liability</h2><p>To the fullest extent permitted by law, JobsLostLive and its affiliates shall not be liable for any indirect, incidental, or consequential damages. Maximum aggregate liability shall not exceed CAD $100.</p></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">11. Indemnification</h2><p>You agree to indemnify and hold harmless JobsLostLive and its affiliates from any claims arising out of your use of the website or violation of these Terms.</p></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">12. Takedown and Dispute Resolution</h2><p>To report content issues, contact <a href="mailto:simon@realcapitolhill.com" className="text-blue-400 hover:underline">simon@realcapitolhill.com</a> with a description of the content and the issue.</p></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">13. Termination</h2><p>We may suspend or terminate your access at any time, with or without notice, for any reason.</p></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">14. Governing Law</h2><p>These Terms are governed by the laws of the Province of Alberta, Canada. Disputes shall be resolved in the courts of Calgary, Alberta.</p></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">15. Changes to These Terms</h2><p>We may update these Terms at any time. Continued use after changes constitutes acceptance.</p></div>
        <div><h2 className="text-lg font-semibold text-white mb-2">16. Contact Us</h2><p>Email: <a href="mailto:simon@realcapitolhill.com" className="text-blue-400 hover:underline">simon@realcapitolhill.com</a><br />Address: [Insert business or mailing address in Calgary, Alberta, Canada]</p></div>
      </section>
      <div className="mt-16 pt-8 border-t border-slate-800 text-xs text-slate-600 flex gap-6">
        <a href="/" className="hover:text-slate-400">Home</a>
        <a href="/privacy" className="hover:text-slate-400">Privacy Policy</a>
      </div>
    </main>
  );
}
